server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由(默认关闭)
      routes:
        - id: payment_routh #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE    #匹配后提供服务的路由地址（lb:// -表示负载均衡）
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由


        - id: payment_routh2 #payment_route2  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**          #断言，路径相匹配的进行路由
            #- Before=2023-07-06T23:30:09.590981+08:00[Asia/Shanghai] #在此时间之前才能访问上面配置的页面
            - After=2023-07-06T22:30:09.590981+08:00[Asia/Shanghai] #在此时间之后才能访问上面配置的页面
            #- Between=2023-07-06T22:30:09.590981+08:00,2023-07-06T23:30:09.590981+08:00 #在此时间段才能访问上面配置的页面
            #- Cookie=username,bmm #表示所发送的请求中必须包含cookie，并且cookie的名字是username
            #- Header=X-Request-Id, \d+    #请求头要有X-Request-Id属性，并且值为整数的正则表达式
            #- Method=GET #请求方法类型必须是GET
            #- 还有其他的，参见官网文档进行个性化定制
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id，值为1024



eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/